[project]
name = "PhysMetDatadoc"
version = "0.1.0"
description = "Data documentation templates and tools for physical metallurgy."
readme = "README.md"
authors = [
    { name = "Jesper Friis", email = "jesper.friis@sintef.no" },
    { name = "Tor S. Haugland", email = "tor.haugland@sintef.no" },
    { name = "Michele Brigadoi", email = "michele.brigadoi@unibo.it" },
]
requires-python = ">=3.12"
dependencies = [
    "pyyaml",
    "tripper[datadoc]",
]

[project.optional-dependencies]
testing = [
    "pytest==9.1.1",
    "pytest-cov==6.0.0",
    "jsonschema>=4.26.0",
    "requests>=2.34.2",
]
pre-commit = ["PhysMetDatadoc[testing]", "pre-commit==4.0.1", "pylint==3.3.4"]
dev = ["PhysMetDatadoc[pre-commit]", "virtualenvwrapper>=4.0.0"]

[project.scripts]
extract-prefixes = "extract_prefixes:main"
oold-converter = "oold_converter.oold_converter:main"
parse-compositions = "parse_compositions:main"
treeweaver = "treeweaver.treeweaver:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Explicitly tell Hatchling where your packages live
[tool.hatch.build.targets.wheel]
packages = [
    "src/extract_prefixes.py",
    "src/parse_compositions.py",
    "src/oold_converter",
    "src/treeweaver",
]

[tool.hatch.build.targets.sdist]
include = ["/src/treeweaver", "/src/oold_converter"]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint.isort]
known-first-party = ["treeweaver", "oold_converter", "extract_prefixes"]
